//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int ID { get; set; }
        public string MetaTitle { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string Tags { get; set; }
    }
}
