//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GroupUser
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool ExpandNews { get; set; }
        public bool Status { get; set; }
        public string Permission { get; set; }
        public string PermissionCatNews { get; set; }
    }
}
